version: "2"

services:

  mariadb:
      image: wodby/mariadb:10.1-2.3.3
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: drupal
        MYSQL_DATABASE: drupal
        MYSQL_USER: drupal
        MYSQL_PASSWORD: drupal
      volumes:
        - ./runtime/mariadb:/var/lib/mysql
        - ./databases:/var/lib/mysql/databases

  php:
      image: wodby/drupal-php:7.1-2.4.3
      restart: unless-stopped
      environment:
        PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
        DB_HOST: mariadb
        DB_USER: drupal
        DB_PASSWORD: drupal
        DB_NAME: drupal
        DB_DRIVER: mysql
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
        PHP_XDEBUG_AUTOSTART: 1
        PHP_XDEBUG: 1
        PHP_XDEBUG_DEFAULT_ENABLE: 1
      volumes:
        - ./:/var/www/html
        - ./runtime/drush:/home/www-data/.drush

  nginx:
      image: wodby/drupal-nginx:8-1.13-2.4.2
      restart: unless-stopped
      depends_on:
        - php
      environment:
        NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
        NGINX_ERROR_LOG_LEVEL: debug
        NGINX_BACKEND_HOST: php
        NGINX_SERVER_ROOT: /var/www/html/docroot
        NGINX_SERVER_NAME: localhost
        NGINX_UPSTREAM_NAME: php
        NGINX_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
        DRUPAL_VERSION: 8 # Allowed: 7, 8.
        VIRTUAL_HOST: casablanca.dev.loc
      volumes:
        - ./:/var/www/html
      networks:
        - default
        - proxy_net

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      VIRTUAL_HOST: casablanca.pma.loc
    volumes:
      - ./docker-runtime/metro:/www/themes/metro
    networks:
      - proxy_net
      - default

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: casablanca.hog.loc
      VIRTUAL_PORT: 8025
    networks:
      - proxy_net
      - default

networks:
  proxy_net:
    external: true